Repository crowdsecurity/hub, pull requests merged in 2022-07, with the labels that each got.

#459 Add Uptime Kuma parser, scenario and collection
  .tests/uptime-kuma-bf/config.yaml
  .tests/uptime-kuma-bf/parser.assert
  .tests/uptime-kuma-bf/scenario.assert
  .tests/uptime-kuma-bf/uptime-kuma-bf.log
  .tests/uptime-kuma-logs/config.yaml
  .tests/uptime-kuma-logs/parser.assert
  .tests/uptime-kuma-logs/scenario.assert
  .tests/uptime-kuma-logs/uptime-kuma-logs.log
  collections/timokoessler/uptime-kuma.md
  collections/timokoessler/uptime-kuma.yaml
  parsers/s01-parse/timokoessler/uptime-kuma-logs.md
  parsers/s01-parse/timokoessler/uptime-kuma-logs.yaml
  scenarios/timokoessler/uptime-kuma-bf.md
  scenarios/timokoessler/uptime-kuma-bf.yaml
Labels: REVIEW

#478 add unifi support
  .index.json
  .tests/dropbear-logs/config.yaml
  .tests/dropbear-logs/dropbear-logs.log
  .tests/dropbear-logs/parser.assert
  .tests/dropbear-ssh-bf/config.yaml
  .tests/dropbear-ssh-bf/dropbear-ssh-bf.log
  .tests/dropbear-ssh-bf/parser.assert
  .tests/dropbear-ssh-bf/scenario.assert
  .tests/unifi-logs/config.yaml
  .tests/unifi-logs/parser.assert
  .tests/unifi-logs/unifi-logs.log
  collections/crowdsecurity/unifi.md
  collections/crowdsecurity/unifi.yaml
  parsers/s00-raw/crowdsecurity/unifi-logs.md
  parsers/s00-raw/crowdsecurity/unifi-logs.yaml
  parsers/s01-parse/crowdsecurity/dropbear-logs.md
  parsers/s01-parse/crowdsecurity/dropbear-logs.yaml
Labels: REQUIRE CROWDSEC CHANGE

#473 Exchange Support
  .index.json
  .tests/exchange-imap-bf/config.yaml
  .tests/exchange-imap-bf/exchange-imap-bf.log
  .tests/exchange-imap-bf/parser.assert
  .tests/exchange-imap-bf/scenario.assert
  .tests/exchange-imap-logs/config.yaml
  .tests/exchange-imap-logs/exchange-imap-logs.log
  .tests/exchange-imap-logs/parser.assert
  .tests/exchange-imap-logs/scenario.assert
  .tests/exchange-pop-bf/config.yaml
  .tests/exchange-pop-bf/exchange-pop-bf.log
  .tests/exchange-pop-bf/parser.assert
  .tests/exchange-pop-bf/scenario.assert
  .tests/exchange-pop-logs/config.yaml
  .tests/exchange-pop-logs/exchange-pop-logs.log
  .tests/exchange-pop-logs/parser.assert
  .tests/exchange-pop-logs/scenario.assert
  .tests/exchange-smtp-bf/config.yaml
  .tests/exchange-smtp-bf/exchange-smtp-bf.log
  .tests/exchange-smtp-bf/parser.assert
  .tests/exchange-smtp-bf/scenario.assert
  .tests/exchange-smtp-logs/config.yaml
  .tests/exchange-smtp-logs/exchange-smtp-logs.log
  .tests/exchange-smtp-logs/parser.assert
  .tests/exchange-smtp-logs/scenario.assert
  collections/crowdsecurity/exchange.md
  collections/crowdsecurity/exchange.yaml
  parsers/s01-parse/crowdsecurity/exchange-imap-logs.yaml
  parsers/s01-parse/crowdsecurity/exchange-pop-logs.yaml
  parsers/s01-parse/crowdsecurity/exchange-smtp-logs.md
  parsers/s01-parse/crowdsecurity/exchange-smtp-logs.yaml
  scenarios/crowdsecurity/exchange-bf.md
  scenarios/crowdsecurity/exchange-bf.yaml
Labels: WIP, REVIEW

#444 Add GitLab parser, scenario and collection
  .tests/gitlab-bf/config.yaml
  .tests/gitlab-bf/gitlab-bf.log
  .tests/gitlab-bf/parser.assert
  .tests/gitlab-bf/scenario.assert
  .tests/gitlab-logs/config.yaml
  .tests/gitlab-logs/gitlab-logs.log
  .tests/gitlab-logs/parser.assert
  .tests/gitlab-logs/scenario.assert
  collections/timokoessler/gitlab.md
  collections/timokoessler/gitlab.yaml
  parsers/s01-parse/timokoessler/gitlab-logs.md
  parsers/s01-parse/timokoessler/gitlab-logs.yaml
  scenarios/timokoessler/gitlab-bf.md
  scenarios/timokoessler/gitlab-bf.yaml
Labels: REQUIRE CROWDSEC CHANGE

#503 Add pterodactyl wings logs collection, parser & scenario
  .tests/pterodactyl-wings-bf/config.yaml
  .tests/pterodactyl-wings-bf/parser.assert
  .tests/pterodactyl-wings-bf/pterodactyl-wings-bf.log
  .tests/pterodactyl-wings-bf/scenario.assert
  collections/lourys/pterodactyl.md
  collections/lourys/pterodactyl.yaml
  parsers/s01-parse/lourys/pterodactyl-wings-logs.md
  parsers/s01-parse/lourys/pterodactyl-wings-logs.yaml
  scenarios/lourys/pterodactyl-wings-bf.md
  scenarios/lourys/pterodactyl-wings-bf.yaml
Labels: NEW, REVIEW

#433 [REQUIRE CROWDSEC CHANGE] Add support for Caddy 2.5 log format
  .index.json
  .tests/caddy-logs/caddy-logs.log
  .tests/caddy-logs/config.yaml
  .tests/caddy-logs/parser.assert
  parsers/s01-parse/crowdsecurity/caddy-logs.yaml
Labels: REQUIRE CROWDSEC CHANGE, REVIEW

#491 JellySeerr Collection
  .tests/jellyseerr-bf/config.yaml
  .tests/jellyseerr-bf/jellyseerr-bf.log
  .tests/jellyseerr-bf/parser.assert
  .tests/jellyseerr-bf/scenario.assert
  .tests/jellyseerr-logs/config.yaml
  .tests/jellyseerr-logs/jellyseerr-logs.log
  .tests/jellyseerr-logs/parser.assert
  .tests/jellyseerr-logs/scenario.assert
  collections/LePresidente/jellyseerr.md
  collections/LePresidente/jellyseerr.yml
  parsers/s01-parse/LePresidente/jellyseer-logs.md
  parsers/s01-parse/LePresidente/jellyseerr-logs.yaml
  scenarios/LePresidente/jellyseerr-bf.md
  scenarios/LePresidente/jellyseerr-bf.yaml
Labels: REVIEW

#475 Add IPv6 to range postoverflow
  .index.json
  .tests/ipv6-postoverflow/config.yaml
  .tests/ipv6-postoverflow/ipv6-postoverflow.log
  .tests/ipv6-postoverflow/parser.assert
  .tests/ipv6-postoverflow/scenario.assert
  postoverflows/s00-enrich/crowdsecurity/ipv6_to_range.md
  postoverflows/s00-enrich/crowdsecurity/ipv6_to_range.yaml
Labels: REVIEW
